version: '3'
services:
  api:
    container_name: app_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: hotpot

