version: '3'
services:
  api:
    container_name: app_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  db:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example