[default]
TITLE = "Hot Pot"
SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://root:toor@database/hotpot'
SECRET_KEY = '55551cc547d71ce68cb6631a'
EXTENSIONS = [
    "hotpot.ext.database",
    "hotpot.blueprint.webui",
    "hotpot.ext.create_db"
]

[development]
SQLALCHEMY_DATABASE_URI = 'sqlite:///hotpot.db'
SECRET_KEY = '55551cc547d71ce68cb6631a'
